version: '3.2'

services:
  web-nginx:
    build: nginx
    restart: always
    networks:
       - spring_demo_net
    ports:
      - "80:80"
    links:
       - web:application
   
  web:
    build: .
    networks:
      - spring_demo_net
    ports:
      - 8080:8080

  spring-demo-mongo:
    image: mongo:3.0.4
    volumes: 
      - mongo-data:/data/db
    networks:
       - spring_demo_net
    ports:
      - 27017

volumes:
  mongo-data:

networks:
  spring_demo_net: